# Your Solution

apiVersion: apps/v1
kind: Deployment
metadata:
  name: task9-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task9-b
  template:
    metadata:
      labels:
        app: task9-b
    spec:
      containers: 
      - name: task9-b
        image: task9.azurecr.io/task9-b:1
        ports:
        - containerPort: 9494
        imagePullPolicy: IfNotPresent
        env:
        - name: DATABASE_URL
          value: "postgresql://task_9_user:59r77M2CaX5P1y02ibNyGPcSyDPewoGv@dpg-crnd19t6l47c73adrn20-a.oregon-postgres.render.com/task_9?sslmode=require"
---
apiVersion: v1
kind: Service
metadata:
  name: task9-b
spec:
  selector:
    app: task9-b
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 9494
      targetPort: 9494


####

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: task9-i
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task9-i
  template:
    metadata:
      labels:
        app: task9-i
    spec:
      containers: 
      - name: task9-i
        image: task9.azurecr.io/task9-i:1
        ports:
        - containerPort: 9898
        imagePullPolicy: IfNotPresent
        env:
        - name: DATABASE_URL
          value: "postgresql://task_9_user:59r77M2CaX5P1y02ibNyGPcSyDPewoGv@dpg-crnd19t6l47c73adrn20-a.oregon-postgres.render.com/task_9?sslmode=require"
---
apiVersion: v1
kind: Service
metadata:
  name: task9-i
spec:
  selector:
    app: task9-i
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 9898
      targetPort: 9898